"""불용어 사전 + 한국어→영어 스톡 검색어 매핑.

Pexels/Pixabay는 영어 검색어에서 결과가 압도적으로 좋다.
자주 나오는 주제어만이라도 영어로 바꿔 주면 자료화면 적중률이 확 올라간다.
사전에 없는 단어는 한국어 그대로 검색한다(그쪽도 한국어 태그가 조금은 있다).

설정에서 `assets.query_map`으로 얼마든지 덧붙일 수 있다.
"""

from __future__ import annotations

# 자료화면을 붙일 가치가 없는 단어들.
STOPWORDS: frozenset[str] = frozenset(
    """
    그것 이것 저것 여기 거기 저기 우리 저희 당신 여러분 자신 자기
    때문 정도 경우 하나 가지 부분 생각 얘기 이야기 말씀 사실 문제
    지금 이제 다음 처음 마지막 오늘날 요즘 아까 나중 아무
    사람 사람들 분들 여기저기 무엇 어디 언제 누구
    진짜 정말 되게 조금 완전 엄청 그냥 약간 아주 매우 굉장히
    이런 저런 그런 어떤 무슨 이렇게 저렇게 그렇게 어떻게
    같이 함께 대해 위해 통해 관련 관해 대한 위한
    하면 하는 해서 하고 되는 되고 있는 있고 없는 없고
    거예요 겁니다 습니다 입니다 인데요 니까 라서 는데
    수요 그거 이거 저거 뭔가 뭐가 이번 저번 다들 모두
    한도 기준 항목 대상 조건 방법 내용 확인 신청 적용 변경 차이 종류
    이유 결과 시점 여부 절차 나머지 대신 자동 각각
    동안 이상 이하 미만 초과 얼마 상관
    """.split()
)

# 한국어 → 영어 스톡 검색어.
KEYWORD_MAP: dict[str, str] = {
    # 돈 / 금융 — 직역이 아니라 "어떤 사진이 나오면 좋은가"로 골랐다.
    # ("한도"를 limit으로 옮겨 봐야 쓸 만한 사진이 안 나온다 → 불용어로 뺐다)
    "예금": "savings deposit",
    "적금": "savings deposit",
    "통장": "bankbook savings account",
    "계좌": "bank account",
    "저축은행": "savings bank",
    "증권사": "brokerage office",
    "예금자보호": "bank vault safe",
    "파산": "bankruptcy",
    "현금": "cash money",
    "저금통": "piggy bank",
    "월급": "salary paycheck",
    "가계부": "budget planner notebook",
    "재테크": "personal finance planning",
    "자산": "wealth assets",
    "금융": "finance",
    # 세금
    "연말정산": "tax return paperwork",
    "공제": "tax deduction",
    "소득공제": "tax deduction documents",
    "세액공제": "tax deduction documents",
    "절세": "tax saving calculator",
    "국세청": "tax office",
    "영수증": "receipt",
    "서류": "documents paperwork",
    "상속": "inheritance family",
    "증여": "gift money family",
    # 집
    "월세": "apartment rent keys",
    "전세": "apartment lease",
    "임대차": "lease contract",
    "계약서": "contract signing",
    "청약": "application form",
    # 의료 / 생활
    "의료비": "hospital medical bill",
    "안경": "eyeglasses",
    "콘택트렌즈": "contact lens",
    "산후조리원": "newborn baby",
    "기부금": "donation charity",
    "물가": "grocery prices",
    "인플레이션": "inflation",
    # 노후 / 연금
    "연금": "retirement pension",
    "퇴직연금": "retirement savings",
    "연금저축": "retirement savings",
    "노후": "retired couple",
    # 증시
    "배당": "dividend stock chart",
    "배당금": "dividend money",
    "공모주": "stock ipo",
    "상장": "stock exchange",
    "증시": "stock exchange",
    "코스피": "stock market chart",
    "주가": "stock chart",
    "차트": "financial chart",
    "수수료": "fee calculator",
    "이자": "interest rate money",
    "환전": "currency exchange",
    "달러": "us dollar",
    "원화": "korean won money",
    # 사람
    "청년": "young adult",
    "직장인": "office worker",
    # 기술 / IT
    "인공지능": "artificial intelligence",
    "에이아이": "artificial intelligence",
    "머신러닝": "machine learning",
    "딥러닝": "deep learning",
    "데이터": "data",
    "빅데이터": "big data",
    "알고리즘": "algorithm",
    "코딩": "coding",
    "프로그래밍": "programming",
    "개발자": "software developer",
    "컴퓨터": "computer",
    "노트북": "laptop",
    "스마트폰": "smartphone",
    "휴대폰": "mobile phone",
    "인터넷": "internet",
    "네트워크": "network",
    "서버": "server",
    "클라우드": "cloud computing",
    "보안": "cyber security",
    "해킹": "hacking",
    "블록체인": "blockchain",
    "비트코인": "bitcoin",
    "암호화폐": "cryptocurrency",
    "로봇": "robot",
    "드론": "drone",
    "반도체": "semiconductor",
    "배터리": "battery",
    "전기차": "electric car",
    "자율주행": "self driving car",
    "가상현실": "virtual reality",
    "메타버스": "metaverse",
    "게임": "video game",
    "앱": "mobile app",
    "웹사이트": "website",
    "화면": "screen",
    "키보드": "keyboard",
    "카메라": "camera",
    "영상": "video",
    "유튜브": "youtube",
    "채널": "channel",
    "구독": "subscribe",
    "조회수": "views",
    "알고리": "algorithm",
    # 경제 / 비즈니스
    "경제": "economy",
    "주식": "stock market",
    "투자": "investment",
    "부동산": "real estate",
    "금리": "interest rate",
    "물가": "inflation",
    "환율": "exchange rate",
    "돈": "money",
    "현금": "cash",
    "은행": "bank",
    "카드": "credit card",
    "월급": "salary",
    "연봉": "annual salary",
    "저축": "savings",
    "대출": "loan",
    "빚": "debt",
    "세금": "tax",
    "보험": "insurance",
    "회사": "office company",
    "기업": "corporation",
    "사업": "business",
    "창업": "startup",
    "스타트업": "startup",
    "마케팅": "marketing",
    "광고": "advertising",
    "브랜드": "brand",
    "고객": "customer",
    "매출": "revenue",
    "수익": "profit",
    "성장": "growth chart",
    "그래프": "graph chart",
    "통계": "statistics",
    "회의": "business meeting",
    "발표": "presentation",
    "계약": "contract signing",
    "면접": "job interview",
    "취업": "employment",
    "이직": "career change",
    "퇴사": "quitting job",
    "직장": "workplace",
    "사무실": "office",
    "재택근무": "remote work",
    # 생활
    "집": "house home",
    "방": "room interior",
    "주방": "kitchen",
    "요리": "cooking",
    "음식": "food",
    "커피": "coffee",
    "카페": "cafe",
    "식당": "restaurant",
    "물": "water",
    "과일": "fruit",
    "채소": "vegetables",
    "고기": "meat",
    "빵": "bread",
    "술": "alcohol drink",
    "옷": "clothes",
    "신발": "shoes",
    "가방": "bag",
    "쇼핑": "shopping",
    "청소": "cleaning",
    "빨래": "laundry",
    "잠": "sleeping",
    "아침": "morning",
    "저녁": "evening",
    "주말": "weekend",
    "휴가": "vacation",
    "여행": "travel",
    "비행기": "airplane",
    "공항": "airport",
    "기차": "train",
    "지하철": "subway",
    "버스": "bus",
    "자동차": "car",
    "자전거": "bicycle",
    "도로": "road",
    "교통": "traffic",
    "도시": "city",
    "시골": "countryside",
    "바다": "ocean",
    "산": "mountain",
    "하늘": "sky",
    "숲": "forest",
    "공원": "park",
    "날씨": "weather",
    "비": "rain",
    "눈": "snow",
    "태양": "sun",
    "지구": "earth planet",
    "우주": "space universe",
    "별": "stars night sky",
    "동물": "animal",
    "강아지": "dog puppy",
    "고양이": "cat",
    "꽃": "flower",
    "나무": "tree",
    # 건강 / 사람
    "건강": "health",
    "운동": "workout exercise",
    "헬스": "gym workout",
    "달리기": "running",
    "요가": "yoga",
    "다이어트": "diet",
    "병원": "hospital",
    "의사": "doctor",
    "간호사": "nurse",
    "약": "medicine pills",
    "스트레스": "stress",
    "우울증": "depression",
    "명상": "meditation",
    "휴식": "relaxing",
    "수면": "sleep",
    "가족": "family",
    "아이": "child kid",
    "아기": "baby",
    "부모": "parents",
    "친구": "friends",
    "연애": "couple dating",
    "결혼": "wedding",
    "학교": "school",
    "학생": "student",
    "공부": "studying",
    "책": "book",
    "도서관": "library",
    "선생님": "teacher",
    "시험": "exam test",
    "졸업": "graduation",
    # 추상 / 연출
    "시간": "clock time",
    "미래": "futuristic",
    "과거": "vintage retro",
    "역사": "history",
    "변화": "transformation",
    "성공": "success",
    "실패": "failure",
    "목표": "goal target",
    "계획": "planning",
    "아이디어": "idea lightbulb",
    "창의": "creativity",
    "질문": "question mark",
    "답": "answer",
    "비밀": "secret",
    "위험": "danger warning",
    "안전": "safety",
    "전쟁": "war",
    "평화": "peace",
    "환경": "environment nature",
    "기후": "climate change",
    "에너지": "energy power",
    "쓰레기": "waste garbage",
    "재활용": "recycling",
    "인구": "crowd people",
    "정부": "government",
    "정치": "politics",
    "법": "law justice",
    "뉴스": "news",
    "언론": "media press",
    "사진": "photography",
    "음악": "music",
    "영화": "cinema movie",
    "예술": "art",
    "디자인": "design",
    "색": "colors",
    "빛": "light",
    "어둠": "darkness",
    "불": "fire",
    "얼음": "ice",
    # 지명 — 그냥 한글로 검색하면 결과가 거의 없다
    "한국": "korea",
    "서울": "seoul",
    "부산": "busan korea",
    "제주": "jeju island",
    "일본": "japan",
    "도쿄": "tokyo",
    "중국": "china",
    "미국": "usa america",
    "뉴욕": "new york city",
    "유럽": "europe",
    "파리": "paris",
    "런던": "london",
    "인도": "india",
    "아프리카": "africa",
}


def merge_map(extra: dict[str, str] | None) -> dict[str, str]:
    """사용자 설정의 매핑을 기본 사전 위에 얹는다."""
    if not extra:
        return KEYWORD_MAP
    merged = dict(KEYWORD_MAP)
    merged.update(extra)
    return merged


__all__ = ["STOPWORDS", "KEYWORD_MAP", "merge_map"]
